title: My blog
description: Nice Things on the Web
author: "Mizan M"

theme: minima

base_url: /
repository: mizandev/mizan.github.io

# Minima social links
github_username: mizandev
linkedin_username: mizanm
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/about.md
  - _pages/archive.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
